### ISSUE TITLE
Feature request: UX Fix top toolbar to allow saving with long content pages without scrolling

### ISSUE THREAD

**Issue by acetinick** [SpinaCMS/Spina#1002]
Hey just a small UX improvement I think would help everyone especially for long pages with lots of parts,  is to have top save toolbar fixed as you scroll so that you can easily save without having to scroll up everytime

![image](https://user-images.githubusercontent.com/571649/158282750-7e9823e1-05fb-4273-92cd-3f5e66c0aab5.png)

**Comment by Bramjetten** [comment]
This is a bit of a CSS-challenge considering the way our current layout is setup, but it'd be nice to make it sticky. One thing to keep in mind is that the rich text part also has a sticky toolbar. Maybe it's enough to make the "Save changes" button sticky.

You can also use Ctrl+S / Cmd+S to save a page btw. You don't necessarily have to use the button.

**Comment by acetinick** [comment]
CTRL+S works for us,  ill close this one
