### ISSUE TITLE
Performance issue: Pages in admin  N+1

### ISSUE THREAD

**Issue by acetinick** [SpinaCMS/Spina#1024]
Hi,

We have hundreds of articles that we have migrated, but now the admin page is unable as there is no pagination, and it takes 10 seconds to load.  Most of it looks to be due to N+1

![image](https://user-images.githubusercontent.com/571649/162546327-fb5889a6-a6c4-4c0a-9003-6431bcc433b5.png)

**Comment by acetinick** [comment]
Yep they are inside an "articles" resouce

**Comment by acetinick** [comment]
Some more logs right before the N+1 queries happen

![image](https://user-images.githubusercontent.com/571649/162575350-ba25429b-6554-4818-b83e-a9d1269cb2ce.png)

**Comment by Bramjetten** [comment]
This N+1 query is unfortunate, but hard to prevent with `ancestry`. We can improve things by adding proper pagination for resources above a certain number of pages. Have to figure out how to do manual ordering in that case as well.

**Comment by Bramjetten** [comment]
Still an issue

**Comment by Bramjetten** [comment]
Also, still planning on fixing this.
