### ISSUE TITLE
Is it possible to have a custom part provided by a plugin?

### ISSUE THREAD

**Issue by moxvallix** [SpinaCMS/Spina#1031]
I have been working on a plugin that would provide topic tags for pages.

It adds a topics table, and a way to create and destroy topics.
However, I also am working on a Custom Part that pairs with the topics plugin.
How do I add the part to my plugin such that Spina can use it? Or can the part only be added in the main project?

**Comment by Bramjetten** [comment]
You can definitely create a new custom part in your own project/gem. Here's a guide on how to do that:
https://spinacms.com/guides/themes-content/how-to-create-custom-content-parts

You can add the following to your `engine.rb` in your plugin:
```ruby
config.to_prepare do
  Spina::Part.register(Spina::Parts::Topic)
end
```

**Comment by moxvallix** [comment]
Ok, awesome thanks! It's working now.
