### ISSUE TITLE
Add social meta tags to page metadata

### ISSUE THREAD

**Issue by iguido95** [SpinaCMS/Spina#1120]
Add social meta tags to page metadata in their own separate tab

<img width="502" alt="CleanShot_2022-06-03_at_14 10 512x" src="https://user-images.githubusercontent.com/10342907/195365994-df9c1615-404c-4fc0-a3f1-54a3cd9746b9.png">

Should be included by adding this code to the page template: 
`<%= social_meta_tags %>`

Overview of social meta tags can be found here:
https://css-tricks.com/essential-meta-tags-social-media/

**Comment by Bramjetten** [comment]
Still on the roadmap
