### ISSUE TITLE
Delete buttons are confusing

### ISSUE THREAD

**Issue by Jonathan-Jacob** [SpinaCMS/Spina#1143]
If you have nested repeaters, you'll end up with two or more delete buttons underneath each other that look exactly the same. I have written some code for changing the button texts from "Delete" to "Delete %{item}" – so far for English, German, and French. This way you can much more easily figure out which exact object you are going to delete.

With your permission I will create the pull request myself.

**Comment by Bramjetten** [comment]
I welcome a PR!

**Comment by Bramjetten** [comment]
Fixed in #1144
