### ISSUE TITLE
[Improvement suggestion] Divider & Header page_parts for labeling & ability to split page_parts into tabs

### ISSUE THREAD

**Issue by KINKCreative** [SpinaCMS/Spina#121]
Hey guys, great great work so far, we are really enjoying Spina! I've used Silverstripe CMS like a maniac and really like where Spina is headed.

Setting up the admin for our new project, I was curious if you can do a "Divider" page part type and a "Header" page part type (non data-entry parts / fields just to organize the CMS a bit). In SilverStripe the headers are given the text and level of header (1-5, so it would spit out h1, h2, h3, h4 or h5 in the form). They also do a thing called "Literal Field" where you basically configure the entire HTML of that particular field, which could come in handy for custom UX fields / adding jQuery plugins etc.

Secondly, are there plans to assign fields to custom tabs on the page if needed?

**Comment by Bramjetten** [comment]
Sounds good. The redesign makes the page form a bit more clear, but I agree that labels and dividers might help.

**Comment by dankmitchell** [comment]
Don't think this is relevant anymore. The feedback on the UI has been nothing but positive 💪
