### ISSUE TITLE
Release for gem supporting view component 3

### ISSUE THREAD

**Issue by Caleb-T-Owens** [SpinaCMS/Spina#1236]
Morning! I'm setting up spina in a project which is using view component 3 and I've found the current release doesn't permit it though there is a commit in main which does increase the supported range. For now, I'll target the git repo but it would be good to know an ETA on when a patch supporting view component 3 will be coming out.

Thanks for the great library, btw!

**Comment by Bramjetten** [comment]
I released v2.15.0! 🎉

**Comment by Caleb-T-Owens** [comment]
Amazing, thanks!
