### ISSUE TITLE
"New page" button disappears when I make a custom page undeletable

### ISSUE THREAD

**Issue by benzado** [SpinaCMS/Spina#1241]
I've just integrated Spina into an existing Rails app (very easy, thank you!) and I'm setting up a theme; specifically I've been defining a lot of Custom Pages. Along the way I noticed that the "New page" button had disappeared!

After some trial and error, I realized it had something to do with whether the custom pages were deletable or not. After digging into the source code, I learned that:

* `NewPageButtonComponent` only renders if there are any view templates available (that makes sense)
* `PagesController` populates the list of templates by calling `Spina::Current.theme.new_page_templates`
* `Theme` excludes view templates based on the result of `is_custom_undeletable_page?`

That method is defined like so:

```ruby
    # Check if view_template is defined as a custom undeletable page
    def is_custom_undeletable_page?(view_template_name)
      @custom_pages.any? { |page| page[:view_template] == view_template_name && !page[:deletable] }
    end
```

So, apparently, if I define a custom page and mark _the page_ undeletable, that also affects whatever _view template_ the page is using, and prevents that view template from being used to create new pages.

As a new user, that is very surprising behavior! I checked the commit history to see if I could learn why the test was added, but [it's present in the repo's initial commit](https://github.com/SpinaCMS/Spina/blob/f875872c62e50ea5b9205d249b275202fc869c37/lib/spina/theme.rb), so it's a mystery to me.

The workaround is very simple (define separate view templates), so it's not going to prevent me from moving forward, but it is confusing and I think either the restriction ought to be removed or an explanation added to the documentation. I'm happy to submit a PR for either but I'll need some guidance first.

**Comment by Bramjetten** [comment]
I agree, this is surprising behavior! I think the config should be more explicit so it's clear what the UI should do. Feel free to open a PR :)

**Comment by benzado** [comment]
Sorry, I don’t understand. Are you suggesting changing the behavior or documenting the existing behavior?

**Comment by dankmitchell** [comment]
I've just come across this on a website too. 

Expected behavior - All templates should be available as a new page, regardless if they are used for a custom page.
