### ISSUE TITLE
Ukrainian localization

### ISSUE THREAD

**Issue by shortys** [SpinaCMS/Spina#1343]
I suggest adding Ukrainian language localization to the system. How do you feel about this?

**Comment by Bramjetten** [comment]
Feel free to open a PR!

**Comment by shortys** [comment]
Can't commit. Github say when try commit:
You don't have permissions to publish to "Spina CMS/Spina" on Github
You need add some access to repo?

**Comment by shortys** [comment]
I'm doing this for the first time.
 Add PR #1344
