### ISSUE TITLE
importmap v2.0 release breaks admin layout

### ISSUE THREAD

**Issue by aseroff** [SpinaCMS/Spina#1358]
The error is `ActionView::Template::Error: undefined local variable or method "javascript_importmap_shim_nonce_configuration_tag"`, which appears to be because it was removed from [importmaps v2 release](https://github.com/rails/importmap-rails/releases/tag/v2.0.0).

**Comment by aseroff** [comment]
If you are facing this problem, you can copy [this helper](https://github.com/SpinaCMS/Spina/blob/main/app/helpers/spina/spina_helper.rb) into your own project, and remove lines 6-7 to not have to pin importmaps to v1 or wait for a spina release.

**Comment by clickworkorange** [comment]
I was stumped by this on my very first test run of SpinaCMS - eventually found this issue and updated `vendor/bundle/ruby/3.1.0/gems/spina-2.17.0/app/helpers/spina/spina_helper.rb` with the new version from #1359, which seems to have fixed the problem. Cheers!
