### ISSUE TITLE
bug:  cannot install the gem

### ISSUE THREAD

**Issue by lsglucas** [SpinaCMS/Spina#1363]
I believe this is related to the newest versions of Rails (>=7.1.2).

I tried running `rails g spina:install` on a clean project, and got the following error:

```cmd
/.gem/gems/activerecord-7.1.3.2/lib/active_record/attribute_methods/serialization.rb:208:in `serialize': missing keyword: :coder If no default coder is configured, a coder must be provided to `serialize`. (ArgumentError)

            raise ArgumentError, <<~MSG.squish
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from /.gem/gems/spina-2.5.0/app/models/spina/account.rb:8:in `<class:Account>'
```

**Comment by callawaywilson** [comment]
I just ran into this issue myself trying to get Spina set up.  The current version `2.18.0` works, make sure that you're not using an older gem version (or not specifying the version like in the install docs) like I did!

**Comment by Bramjetten** [comment]
Sorry for the confusion! I've updated the docs.
