### ISSUE TITLE
rails spina:install cannot be found

### ISSUE THREAD

**Issue by tmpearsall** [SpinaCMS/Spina#1374]
Background:

  ruby  3.1.2
  gem "rails", "~> 7.1.3", ">= 7.1.3.3"
  
  new rails app (try2spina)
  rails activestroage:install created its db migration
  spina added to the Gemfile, no version number specified
  bundle install  installed spina version 2.5.0
  attempted to execute rails spina:install

Error:
  try2spina % rails spina:install
  Unrecognized command "spina:install"
  Did you mean?  yarn:install
  
Tried this next
   rails g spina:install
   create  config/initializers/spina.rb
    create  config/initializers/mobility.rb
    route  mount Spina::Engine => '/'
    rake  spina:install:migrations

Result:
  Migrations generated
  Error:
    /.rvm/gems/ruby-3.1.2/gems/activerecord-7.1.3.3/lib/active_record/attribute_methods/serialization.rb:208:in `serialize': missing keyword: :coder If no default coder is configured, a coder must be provided to `serialize`. (ArgumentError)

Then I added:

    config.active_record.default_column_serializer = YAML
    #PublicActivity#parameters serialisation
    config.active_record.yaml_column_permitted_classes += [...]
 
 to application.rb

  Result:

   navigated to /admin

  Error:

   NoMethodError (undefined method `theme' for nil:NilClass
        Spina::Current.theme ||= ::Spina::Theme.find_by_name(current_account.theme)
                                                                            ^^^^^^):
        spina (2.5.0) app/controllers/concerns/spina/current_theme.rb:13:in `current_theme'

In all cases questions, as described in the docs, were not asked.

What should I try next?

**Comment by pashachek** [comment]
I works for me:

config.active_record.yaml_column_permitted_classes = [ActiveSupport::TimeWithZone,
ActiveSupport::TimeZone,
ActiveSupport::HashWithIndifferentAccess,
BigDecimal,
Date,
String,
Symbol,
Time]

**Comment by pashachek** [comment]
Check your spina version installed.
My issues solved with gem 'spina', "2.18.0".

I found when had "gem 'spina'" in my Gemfile it causes installation of spina 2.5

**Comment by tmpearsall** [comment]
Thanks for the comments, I will give them a shot.
