### ISSUE TITLE
When trying to do an initial install silently it still fails checking for the theme.

### ISSUE THREAD

**Issue by donnoman** [SpinaCMS/Spina#1382]
```
app-1  | bin/rails aborted!
app-1  | NoMethodError: undefined method `theme' for nil (NoMethodError)
app-1  |
app-1  |       return if account.theme.present? && (silent_install? || !no?("Theme '#{account.theme}' is set. Skip? [Yn]"))
app-1  |                        ^^^^^^
```

on fresh install after

  ./bin/rails db:create
  ./bin/rails spina:install --silent

**Comment by donnoman** [comment]
is there a difference between using ./bin/rails spina:install --silent vs ./bin/rails g spina:install --silent ?

I think I saw it both ways in the docs. I'm using the latter now, and not having this issue anymore

**Comment by Bramjetten** [comment]
The —silent flag only works on the generator. rails spina:install is a shortcut using a Rake task.

**Comment by donnoman** [comment]
Thanks that explains what I was observing.  Do we close this, or is the right thing to do emit a warning when running `run spina:install with --silent`

**Comment by donnoman** [comment]
clearly --silent does have an impact when running without the generator... whats happens here is a suprise, perhaps it should fully work even without the generator, if it otherwise does most of what its supposed to correctly in this context.

**Comment by Bramjetten** [comment]
The silent generator is definitely broken, that should be fixed! It's not really clear to me why we really need a silent option though. Why would you use it?

**Comment by donnoman** [comment]
I'm using it to seed a fully automated docker installation. I'd rather silent just read some environment variables instead of canned values.  But if silent went away I suppose I could do the needful with seeds.rb and a db:prepare before calling g spina:install
