### ISSUE TITLE
Outdated deprecation message

### ISSUE THREAD

**Issue by clemenshelm** [SpinaCMS/Spina#1384]
I'm using the draper gem in my application which stores decorators in `app/decorators`. Now spina gave me the warning:

> using app/decorators is deprecated in favor of app/overrides. Read more about overriding Spina at spinacms.com/guides

I'm not overriding spina decorators, so the message is misleading anyway.

However, when I tried to upgrade to Rails 7.2 today, this became a blocker because apparently `ActiveSupport::Deprecation.warn` isn't available anymore.

```
NoMethodError: private method `warn' called for ActiveSupport::Deprecation:Class (NoMethodError)

          ActiveSupport::Deprecation.warn("using app/decorators is deprecated in favor of app/overrides. Read more about overriding Spina at spinacms.com/guides")
```

What would be the best solution here? Could you just remove the warning?

**Comment by Bramjetten** [comment]
Let's just remove the deprecation warning altogether 👍
