### ISSUE TITLE
Tailwind not applying

### ISSUE THREAD

**Issue by sunkenquest** [SpinaCMS/Spina#1390]
How to configure the tailwind css into spina? It doesnt seem to work on my end but when i try to create a scaffold and apply tailwind to it, it woks.

This is the demo page (note that Demo should have a style) `<h1 style="font-bold text-4xl"><%= current_page.title %></h1>`
![image](https://github.com/user-attachments/assets/802b23c7-04f1-4eaf-9d42-0068377a294f)

This is the scaffold with correct configuration of tailwind
![image](https://github.com/user-attachments/assets/e3c242e7-2a3c-478b-8da8-127ff73bc945)

**Comment by Bramjetten** [comment]
You should probably use something like the `tailwindcss-rails` gem to install Tailwind in your project. This is not something Spina does for you.

**Comment by sunkenquest** [comment]
I see, Thank you !
