### ISSUE TITLE
Login security features

### ISSUE THREAD

**Issue by lukaVarga** [SpinaCMS/Spina#260]
Hello, in the interest of securing the admin part against potential bruteforce or similar attacks, would it not be sensible to add a login lock after a certain amount of failed login attempts? 
Meaning, if I try to login and fail 10 times (for instance), I get blocked for eg. 10 minutes and cannot attempt login until that time passes? Perhaps even automatically send an email to that user notifying them that there were several unsuccessful login attempts (in case it wasn't them who tried to login)?
10 attempts is more than enough for a normal user who just miss-typed their password or who uses a couple of passwords and couldn't remember which one was used here.

Furthermore, while trying to login - you do get the "username or password was incorrect" message, but in the "Forgot password" option, you get a notification if that user does not exist. So using the forget password feature, one can plainly see which user emails are actually used and, with it, remove one variable regarding which part of login info was incorrect. 

My suggestion here, for the forgot password vulnerability is, that you always render a standard message, something in the lines of "An email with instructions regarding password change has been sent to email foo@bar.com, provided that a user with such an email exists." 
Or request both username and user email for the forgot password option. 
(On that note, it would also be good if we could control the content of the email that's sent. While I don't mind being sent "You forgot your password dummy." in email to myself, it certainly wouldn't seem very professional if that email was sent to a client.

The final thing that would be awesome is if we could expire a user session with some setting (in the initializer, for example) after a certain amount of inactivity.

**Comment by Bramjetten** [comment]
These are great suggestions, could you create these as separate issues?

**Comment by lukaVarga** [comment]
@Bramjetten - sorry for the late reply, I've been away. Sure, I can create separate issues, but I reckon that is something you will be implementing?
