### ISSUE TITLE
Add more social media in Preferences

### ISSUE THREAD

**Issue by falexandrou** [SpinaCMS/Spina#273]
Currently, only 3 entries are displayed in Social media tab in Preferences, one of them is Google+ which I thought it was a bit dated, so I took the chance to add a few more.

Added: YouTube, Instagram, Linkedin in #272

**Comment by Bramjetten** [comment]
We’re planning on refactoring those preferences to allow people to add any number of social media references using a key/value store.

**Comment by falexandrou** [comment]
Do you think my PR #272 would work as a temporary enhancement though? 
PS. I'd be more than happy to contribute into future enhancements

**Comment by daltonrenaldo** [comment]
any progress on this?

**Comment by dankmitchell** [comment]
This has been solved with https://github.com/SpinaCMS/Spina/pull/272
