### ISSUE TITLE
How to make custom navigation

### ISSUE THREAD

**Issue by Rama-n** [SpinaCMS/Spina#296]
In the documentation it says, we can make our custom navigation with define navigations in our theme's config file. But after that how? i mean how can we make separate between main navigation and custom navigation when create a page?

**Comment by Rama-n** [comment]
and in views in navigation.html.erb i look there is 

- pages = current_spina_user.present? ? Spina::Page.active : Spina::Page.live
- menu = Spina::Pages::MenuPresenter.new(pages.in_menu.arrange(order: :position), self, @page)

can someone tell me about the format , how to get navigation page data. Cause there is no documentation about this things. The idea is i want to get value of navigation with specific of type navigation , is that navigation belongs to main navigation or custom navigation

**Comment by jirawat050** [comment]
what you want have to?vecause?

**Comment by dankmitchell** [comment]
Add wiki to explain how to setup the navigation

**Comment by yasmineezequiel** [comment]
I am quite new with CMS and I have few doubts about Spina:

1. Is there a way I can render one of my view pages into the nav bar?

view/default/pages/shared/_navigation.html.slim
```
- presenter = Spina::MenuPresenter.new(Spina::Page.all)  **#here instead of .all I tried .about and it gave me undefined method error.**

- presenter.config.menu_css = 'cover-container d-flex w-100 h-100 p-3 mx-auto flex-column'
- presenter.config.list_css = 'inner'
- presenter.config.list_tag_css = 'nav nav-masthead justify-content-center'
- presenter.config.link_tag_css = 'nav-link'


= presenter.to_html
```
and I am rendering into the default/application 
```
    = render 'default/shared/navigation'
```

2. Is there any method for clearing cache? I have tried to add a new attribute into the home page of image but the input box doesn't display and I am guessing that is a cache issue but if I should take another approach please let me know, below is the config/theme/default:
```
::Spina::Theme.register do |theme|

  theme.name = 'default'
  theme.title = 'Default Theme'

  theme.page_parts = [{
    name:           'text',
    title:          'Text',
    partable_type:  'Spina::Text'
  }, {
    name:           'dec',
    title:          'Ingress',
    partable_type:  'Spina::Text'
  }, {
    name:           'headline',
    title:          'Headline',
    partable_type:  'Spina::Line'
  }]

  theme.view_templates = [{
    name:         'homepage',
    title:        'Homepage',
    page_parts:   ['headline', 'dec', 'text']
  }, {
    name:         'show',
    title:        'Default',
    description:  'A simple page',
    usage:        'Use for your content',
    page_parts:   ['headline', 'text']
  }, {
    name:         'omhealthintegrator',
    title:        'Om Health Integrator',
    page_parts:   ['headline', 'dec', 'text', 'image']    ** # here is where I tried to add image attribute **
  },
  {
    name:         'för_dig_som_vill_få_bättre_levnadsvanor',
    title:        'För dig som vill få bättre levnadsvanor',
    page_parts:   ['headline', 'dec', 'text', 'image']   ** #here is where I tried to add image attribute **
  }
]

  theme.custom_pages = [{
    name:           'homepage',
    title:          'Homepage',
    deletable:      true,
    view_template:  'homepage'
  }, {
    name:           'omhealthintegrator',
    title:          'Om Health Integrator',
    deletable:      true,
    view_template:  'omhealthintegrator'
  },
  {
    name:           'för_dig_som_vill_få_bättre_levnadsvanor',
    title:          'För dig som vill få bättre levnadsvanor',
    deletable:      true,
    view_template:  'för_dig_som_vill_få_bättre_levnadsvanor'
  }
]

  theme.navigations = [{
    name: 'mobile',
    label: 'Mobile'  
  }, {
    name: 'main',
    label: 'Main navigation',
    auto_add_pages: true
  }]

end
````

**Comment by Bramjetten** [comment]
@yasmineezequiel Welcome! Feel free to join our Slack community: https://slack-spinacms.herokuapp.com. It's great. :)

1. If you want to render just one page, it's easier to just get that page and manually render it using the `menu_title`  and `materialized_path` methods. If you want to render a collection of pages, you can just shove that into `Spina::MenuPresenter.new` as an argument. It also accepts `Spina::Navigation` objects to easily create multiple menus.

2. Any time you make changes to your theme configurion, you need to restart the server.
