### ISSUE TITLE
Setting default locale, backend and frontend

### ISSUE THREAD

**Issue by jjf21** [SpinaCMS/Spina#351]
Hello guys, 
I can't find a way to change the **backend locale** properly, 
neither to change the **default locale** for the website (from english to french), 
have tried to edit the I18N initializer with:

```
  I18n.available_locales = [:fr, :en]
  I18n.default_locale = :fr
```

Backend is now in FR, 
but in frontend:

```
'localhost:3000/' --> 404
'localhost:3000/fr' --> OK
'localhost:3000/en' --> 404
```

if someone can help

**Comment by Bramjetten** [comment]
Hey! You can use an initializer to setup languages for your website:

```ruby
Spina.configure do |config|
  # Set locales
  config.locales = [:nl, :en, :de, :fr]
end
```

**Comment by jjf21** [comment]
Hey @Bramjetten, thanks for your quick reply !

Yes, I've tried this but, it won't change the backend locale.

I've already this in my Spina initializer:
```
# Set locales
  config.locales = [:fr, :en]
```

**Comment by Bramjetten** [comment]
It's a combination of the two. The locales in your Spina initializer define the locales you want to have for your website, and the locales in application.rb are for your backend.

**Comment by Bramjetten** [comment]
It might help if you resaved your pages after changing your locale settings.

**Comment by dankmitchell** [comment]
@jjf21 if you're happy to, please close this issue
