### ISSUE TITLE
No bitcoin / ethereum support options

### ISSUE THREAD

**Issue by abunsen** [SpinaCMS/Spina#352]
Could you please add anonymous support options? Preferably for ETH, BTC, XMR and LTC?

**Comment by Bramjetten** [comment]
We would gladly add crypto support options. How would you recommend doing that?

**Comment by Bramjetten** [comment]
Gitcoin?

**Comment by abunsen** [comment]
You could just drop some addresses at the bottom of the readme :)

**Comment by dankmitchell** [comment]
@Bramjetten do you want to collect donations via crypto? If so, add your addresses to the readme, else close this issue ;-p
