### ISSUE TITLE
ActiveStorage install problem

### ISSUE THREAD

**Issue by jaspervanbrian** [SpinaCMS/Spina#381]
Hello, is it just me or "rails active_storage:install" won't work?
First, I encountered this problem on development when I am trying to create new page. Suddenly the image is 'nil' because no ActiveStorage installed. I have the needed dependencies but it seems it don't work.

Expected behavior:

`Copied migration 20180703215057_create_active_storage_tables.active_storage.rb from active_storage`

Actual behavior:

`rails aborted!
Don't know how to build task 'active_storage:install:migrations' (see --tasks)`
 
System config
rails 5.2
ruby 2.5.0

**Comment by dankmitchell** [comment]
You need `rails active_storage:install:migrations`

**Comment by jaspervanbrian** [comment]
Ok so `active_storage:install:migrations` didn't quite work well but the workaround for this is

`rails app:active_storage_install:migrations`

Thanks for the feedback
