### ISSUE TITLE
Are there any guides on how to integrate Spina into an existing project?

### ISSUE THREAD

**Issue by raman162** [SpinaCMS/Spina#382]
Good day. I was reviewing the docs for SPINA and it seems like there were only docs on how to setup with a new rails app. I was interested if there is a guide to hook into an existing rails app which already has their own form of admins. etc

**Comment by Bramjetten** [comment]
It's not different than setting it up for a new app. Simply mount it where you want to use it. You can change the generated admin path in `spina.rb`.

**Comment by abunsen** [comment]
@raman162 - AFAIK, you cannot use your own authentication / authorization system, you have to use Spina's. Beyond that, you can just mount it like @Bramjetten said, you'd put this in your `routes.rb`:

`mount Spina::Engine => '/your-path-here'`

Then run your `rails g spina:install` from the project root 😃

**Comment by abunsen** [comment]
On this note, is there a way to make Spina inherit the projects active_storage base_url / host?

**Comment by dankmitchell** [comment]
This issue has gone off track so closing. If the last comment is still an issue please create a new issue.
