### ISSUE TITLE
How to resolve image(s) URL?

### ISSUE THREAD

**Issue by ReekenX** [SpinaCMS/Spina#384]
For 1.0 Spina how to get uploaded Image URL? Spent few hours on this and the only hacky solution I found was: 

    # we are in /app/views/default/pages/*.html.erb
    Rails.application.routes.url_helpers.rails_blob_path(image.file, only_path: true)

Variable `image` here is `Spina::Image`.

Going with things like `url_for(image)` would raise `undefined method attachment_path [..]`

**Comment by Bramjetten** [comment]
Did you try `main_app.url_for(`?

**Comment by ReekenX** [comment]
Oh, now I get it. It works.

Thanks for fast reply. Awesome CMS, already going with 5th project with it.
