### ISSUE TITLE
Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for ...

### ISSUE THREAD

**Issue by montdidier** [SpinaCMS/Spina#390]
db/migrate/20180816082557_create_spina_tables.spina.rb

using Rails 5.2.1

**Comment by johnsampson** [comment]
I just received this error as well.  fwiw, as @montdidier has more or less specified, a quick fix for those running into this issue is to explicitly define your rails version on this line of db/migrate/DATESTAMP_create_spina_tables.spina.rb:

>  class CreateSpinaTables < ActiveRecord::Migration[5.2]

**Comment by dankmitchell** [comment]
Cannot replicate on current release.

Version numbers were added here - https://github.com/SpinaCMS/Spina/commit/2b2c8de5652de5844a40aa944c672e2f09cc36a0#diff-faca9baef4b08f66fd6bec9cc4d91a11
