### ISSUE TITLE
Undefined variables on fresh install

### ISSUE THREAD

**Issue by legacy370** [SpinaCMS/Spina#392]
With a fresh install of Spina, when I first try to access the application, it bombs on
Undefined variable: "$helvetica".
Undefined variable: "$georgia". 
After changing those variables to $font-stack-helvetica and $font-stack-georgia, found in </ruby-2.4.1/gems/spina-template-0.4.2/app/assets/stylesheets/spina/_configuration.sass"  , I then encountered
Undefined mixin 'row'.

**Comment by Bramjetten** [comment]
Sounds like a dependency on bourbon. Are you using the latest version?

Op vrijdag 31 augustus 2018, om 20:26 heeft Norman Snyder het volgende geschreven:

**Comment by legacy370** [comment]
spina-1.0.3
bourbon (5.1.0)

**Comment by Bramjetten** [comment]
We dropped bourbon a couple of versions ago. The errors you’re seeing shouldn’t come from Spina. Could you try updating to the master branch?

Op vrijdag 31 augustus 2018, om 20:47 heeft Norman Snyder het volgende geschreven:

**Comment by legacy370** [comment]
Fantastic!  I removed the bourbon gem entirely from my system, and removed both spina 0.8.3 and spina 1.0.3.  Then did a bundle update, after adding gem 'spina', '~> 1.0' to the Gemfile.
It now comes up cleanly.
