### ISSUE TITLE
Error creating User (unknown attribute 'admin' for User)

### ISSUE THREAD

**Issue by luismnzr** [SpinaCMS/Spina#396]
I'm not being able to install Spina beacause of an error while creating a user.

After it prompts me for an email and password, this happens:

`Please enter an email address for your first user: [admin@domain.com]
Create a temporary password: [password]
/usr/local/bundle/gems/activemodel-5.2.1/lib/active_model/attribute_assignment.rb:53:in `_assign_attribute': unknown attribute 'admin' for User. (ActiveModel::UnknownAttributeError)
        from /usr/local/bundle/gems/activemodel-5.2.1/lib/active_model/attribute_assignment.rb:44:in `block in _assign_attributes'
        from /usr/local/bundle/gems/activemodel-5.2.1/lib/active_model/attribute_assignment.rb:43:in `each'
        from /usr/local/bundle/gems/activemodel-5.2.1/lib/active_model/attribute_assignment.rb:43:in `_assign_attributes'
        from /usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/attribute_assignment.rb:23:in `_assign_attributes'
        from /usr/local/bundle/gems/activemodel-5.2.1/lib/active_model/attribute_assignment.rb:35:in `assign_attributes'
        from /usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/core.rb:314:in `initialize'
        from /usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/inheritance.rb:66:in `new'
        from /usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/inheritance.rb:66:in `new'
        from /usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/persistence.rb:35:in `create'
        from /usr/local/bundle/gems/spina-1.0.3/lib/generators/spina/install_generator.rb:68:in `create_user'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `each'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `map'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `invoke_all'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/group.rb:232:in `dispatch'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /usr/local/bundle/gems/railties-5.2.1/lib/rails/generators.rb:276:in `invoke'
        from /usr/local/bundle/gems/railties-5.2.1/lib/rails/commands/generate/generate_command.rb:26:in `perform'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /usr/local/bundle/gems/railties-5.2.1/lib/rails/command/base.rb:65:in `perform'
        from /usr/local/bundle/gems/railties-5.2.1/lib/rails/command.rb:46:in `invoke'
        from /usr/local/bundle/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<main>'
        from /usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        from /usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        from /usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        from /usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        from /usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        from /usr/local/bundle/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
        from /usr/local/bundle/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
        from /usr/local/bundle/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
        from /usr/src/bin/rails:6:in `<main>'`

I've seen similar errors, but I have not being able to fix this. Any ideas on what might be going on?

**Comment by dankmitchell** [comment]
Is this a new rails project?
