### ISSUE TITLE
problem about libicui18n on mac 

### ISSUE THREAD

**Issue by pointcloud-ai** [SpinaCMS/Spina#397]
The command i type as below :
`rails g spina:install`
`rails s `
The problem messages are here :
```
Showing /Users/hanyu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spina-1.0.3/app/views/spina/admin/sessions/new.html.haml where line #2 raised:

dyld: Symbol not found: __ZTVN6icu_6113FieldPositionE
  Referenced from: /usr/local/bin/node
  Expected in: /usr/local/opt/icu4c/lib/libicui18n.61.dylib
 in /usr/local/bin/node
```
============I make soft link libicui18n.61.dylib to libicui18n.62.dylib
$ ls -l libicui18n*
lrwxr-xr-x  1 hanyu  staff       19 11  9 19:45 libicui18n.61.dylib -> libicui18n.62.dylib
-rw-r--r--  1 hanyu  staff  2546336 11  9 19:03 libicui18n.62.1.dylib
lrwxr-xr-x  1 hanyu  staff       21  6 21 17:59 libicui18n.62.dylib -> libicui18n.62.1.dylib
-r--r--r--  1 hanyu  staff  4498152  6 21 17:59 libicui18n.a
lrwxr-xr-x  1 hanyu  staff       21  6 21 17:59 libicui18n.dylib -> libicui18n.62.1.dylib

**Comment by Bramjetten** [comment]
Can you create a new rails app successfully?

**Comment by pointcloud-ai** [comment]
I grade node can fix it 
brew upgrade node 
thx
