### ISSUE TITLE
Can SpinaCMS support multiple languages?

### ISSUE THREAD

**Issue by pointcloud-ai** [SpinaCMS/Spina#398]
How can i use SpinaCMS to support  english and one more language?

**Comment by Bramjetten** [comment]
Yes

**Comment by pointcloud-ai** [comment]
How to enable multiple languages support?  Can i try it on the spinacms.com source code ?

**Comment by dankmitchell** [comment]
It’s very straight forward. Open the spina initialiser file  and you’ll see what todo.

Yes, you can clone the spinacms website source code.

Check the SpinaCMS organisation on Github
