### ISSUE TITLE
How to add youtube player on SpinaCMS editor ?

### ISSUE THREAD

**Issue by pointcloud-ai** [SpinaCMS/Spina#401]
How to add  pre section and youtube player on SpinaCMS editor ?

I can see below content can show on  SpinaCMS.com . 
```
<pre>
<code class="hljs nginx"><span class="hljs-string">'spina'</span><span class="hljs-attribute">gem</span> 
</code>
</pre>
```
`
<div tabindex="0" class="plyr plyr--youtube plyr--video"><div class="screencast-player plyr__video-wrapper plyr__video-embed"><div id="youtube-16"></div></div></div>`

I add above code on SpinaCMS.com’s editor , but it show the raw html code only.

**Comment by dankmitchell** [comment]
Spina uses Trix so you should refer to their documentation for guidance on extending it - https://github.com/basecamp/trix

FYI there is a slack channel that you might like to join to get a fast response on general Spina questions - https://slack-spinacms.herokuapp.com/
