### ISSUE TITLE
How to response scaling display  for uploaded image in text content

### ISSUE THREAD

**Issue by pointcloud-ai** [SpinaCMS/Spina#402]
How to response scaling  for uploaded image display.

I add below css  in _guide.sass [Project : SpinaCMS.com ] to make image auto scale when display on mobile view. but the image is distorted. Because the image had been resize as "800x800" when it had been insert to page‘s content。 So it had been hardcode width attribute as 800px。
How can i make the uploaded image which  in text content to show without distorted and  auto scaling on mobile ?

Reference code as below：

` app/views/spina/admin/media_picker/select.js.erb`
`trigger('image-insert', '<%= main_app.url_for(@image.variant(resize: "800x800")) %>');`

```
.guide-content
  margin-left: 20px
  max-width: 740px
  padding: 20px 0

  img
      box-shadow: 0 
      display: block
      transition: transform 1s ease
      max-width: 100%
```

**Comment by exc22** [comment]
As in one of your previous Issues in comments was written. 
there is a slack channel that you might like to join to get a fast response to general Spina questions - https://slack-spinacms.herokuapp.com/
Because this is not Spina issue.

**Comment by dankmitchell** [comment]
This is not a spina issue. 

I'd suggest you have two images (or more) then hide and show based on viewport width.

Text on images isn't recommended for SEO reasons anyway.
