### ISSUE TITLE
undefined method `error_explanation!' from plugin docs

### ISSUE THREAD

**Issue by crabbits** [SpinaCMS/Spina#403]
Hey! First off all this project is awesome I switched from refinery yesterday probably not going back :)

Going through the docs to create a new plugin [here](https://github.com/SpinaCMS/Spina/wiki/How-to-create-a-plugin) I get an undefined method `error_explanation!` rendering the form. After searching the repo I couldn't find anything referencing that method. 

Here's the code from the docs -

```
= form_for [:admin, @event], html: {autocomplete: "off"} do |f|
  - content_for :notification_alert do
    = error_explanation!(@event)
```

I probably missed something but I can't see where. To fix it I just used the following from spina/admin/pages/_form.html.haml and it works fine -

```
- if @post.errors.any?
  - content_for :notifications do
    .notification.notification-danger.animated.fadeInRight
      = icon('exclamation')
      .notification-message
        =t 'spina.notifications.alert'
        %small= @post.errors.full_messages.join('<br />').html_safe
      = link_to '#', data: {close_notification: true} do
        = icon('cross')
```

Just flagging it incase I haven't missed anything and the docs need to be updated. If they do I'm happy to do it :) Or if I've missed something please let me know.

Thanks

**Comment by dankmitchell** [comment]
See an updated example here https://github.com/SpinaCMS/spina-blog/blob/master/app/views/spina/admin/blog/categories/_form.html.haml#L2

Docs needs updating 👍
