### ISSUE TITLE
ActiveStorage::InvariableError on Media Library page

### ISSUE THREAD

**Issue by toommz** [SpinaCMS/Spina#411]
It appears that a buggy image file already uploaded can crash the whole media library feature, as it tries to show a variant of that file that cannot be processed by ImageMagick.

A simple ActiveStorage::Attachement#variable? check may temper the problem before linking to the variant:

[Here](https://github.com/SpinaCMS/Spina/blob/e7902d8cfac1c4f4a8cb768dafee927ba25cf345/app/views/spina/admin/images/_image.html.haml#L9)

I'm still investing why this image file in particular caused the error.

**Comment by Bramjetten** [comment]
Could you create a PR for this?

**Comment by toommz** [comment]
Done in #412 :)
