### ISSUE TITLE
Should support i18n?

### ISSUE THREAD

**Issue by lanzhiheng** [SpinaCMS/Spina#451]
This project doest not support i18n for the content of the page right?

**Comment by Bramjetten** [comment]
Yes it does. Spina uses the Mobility gem for supporting multiple languages.

**Comment by lanzhiheng** [comment]
@Bramjetten Yeah, I got it. But another question is that how can I show the multiple language input field in admin page?

![image](https://user-images.githubusercontent.com/8858472/62477100-db35cb00-b7da-11e9-990f-b28784aebea7.png)

I can't find the config in document. Do I need other plugins?

**Comment by Bramjetten** [comment]
After setting up multiple languages in `config/initializers/spina.rb` you need to make sure you restart the server.

**Comment by lanzhiheng** [comment]
@Bramjetten Oh no, It work not it is hard to find the configuration. I think we need add it to our document. Do you mind I create a pull request for it.

**Comment by Bramjetten** [comment]
👍

Verstuurd vanaf mijn iPhone
