### ISSUE TITLE
Image upload not working

### ISSUE THREAD

**Issue by StefKors** [SpinaCMS/Spina#471]
I'm new to ruby on rails, after doing the setup from the video turial I get stuck on uploading an image

<img width="2016" alt="Screenshot 2019-10-08 at 15 54 56" src="https://user-images.githubusercontent.com/11800807/66401879-2ee3b100-e9e4-11e9-8066-73d19d11453f.png">

Any suggestions on how to solve this?

**Comment by Bramjetten** [comment]
Did you setup ActiveStorage correctly?

**Comment by StefKors** [comment]
To be honest I'm not sure, how should I check this? 

not sure if related but when I currently try to get the page to show with only the title I get this:

<img width="1055" alt="Screenshot 2019-10-08 at 15 58 53" src="https://user-images.githubusercontent.com/11800807/66402348-fbeded00-e9e4-11e9-8b5a-ae315f487e62.png">

**Comment by Bramjetten** [comment]
This might be related to Rails 6. It doesn't include a javascript.js file in the asset pipeline anymore, you can delete that line in the layout. You can either use the current version of Spina with Rails 5.2 or you can try to use my latest branch (which includes the Rails 6 upgrade)

**Comment by StefKors** [comment]
hey that makes sense actually. should I specify a version or branch for spina in the gemfile?

**Comment by StefKors** [comment]
added it like this: `gem 'spina', :git => "https://github.com/Bramjetten/Spina.git", :branch => "rails6"`. Did bundle install and it resulted in various similar error which the admin panel working but the public facing pages erroring because of missing .js files. (now it's `application.js`)

**Comment by Bramjetten** [comment]
That's because the `application.js` files *are* missing. You can just delete that `javascript_include_tag` line.

**Comment by StefKors** [comment]
Thanks that solved it indeed
