### ISSUE TITLE
Unable to create first user

### ISSUE THREAD

**Issue by katielentes** [SpinaCMS/Spina#492]
I'm just starting with Spina and get this error after I try to create a password for my first user. I'm adding this to an existing app.

Please enter an email address for your first user: [admin@domain.com]
Create a temporary password: [password]
Traceback (most recent call last):
	41: from -e:1:in `<main>'
	40: from /Users/katielentes/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	39: from /Users/katielentes/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	38: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:287:in `load'
	37: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	36: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:287:in `block in load'
	35: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:287:in `load'
	34: from /Users/katielentes/mealhand/bin/rails:9:in `<top (required)>'
	33: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
	32: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	31: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `block in require'
	30: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
	29: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/railties-5.0.7.2/lib/rails/commands.rb:18:in `<top (required)>'
	28: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	27: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:60:in `generate'
	26: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:145:in `generate_or_destroy'
	25: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:138:in `require_command!'
	24: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
	23: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	22: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `block in require'
	21: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
	20: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/railties-5.0.7.2/lib/rails/commands/generate.rb:13:in `<top (required)>'
	19: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/railties-5.0.7.2/lib/rails/generators.rb:180:in `invoke'
	18: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	17: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	16: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	15: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	14: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	13: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	12: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	11: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	10: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/spina-0.12.0/lib/generators/spina/install_generator.rb:68:in `create_user'
	 9: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/activerecord-5.0.7.2/lib/active_record/persistence.rb:33:in `create'
	 8: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/activerecord-5.0.7.2/lib/active_record/inheritance.rb:65:in `new'
	 7: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/activerecord-5.0.7.2/lib/active_record/inheritance.rb:65:in `new'
	 6: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/activerecord-5.0.7.2/lib/active_record/core.rb:319:in `initialize'
	 5: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/activemodel-5.0.7.2/lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
	 4: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/activerecord-5.0.7.2/lib/active_record/attribute_assignment.rb:26:in `_assign_attributes'
	 3: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/activemodel-5.0.7.2/lib/active_model/attribute_assignment.rb:39:in `_assign_attributes'
	 2: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/activemodel-5.0.7.2/lib/active_model/attribute_assignment.rb:39:in `each'
	 1: from /Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/activemodel-5.0.7.2/lib/active_model/attribute_assignment.rb:40:in `block in _assign_attributes'
/Users/katielentes/.rvm/gems/ruby-2.6.1@mealhand/gems/activemodel-5.0.7.2/lib/active_model/attribute_assignment.rb:48:in `_assign_attribute': unknown attribute 'admin' for User. (ActiveModel::UnknownAttributeError)

**Comment by Bramjetten** [comment]
I believe your app might me interfering with the `Spina::User`. Perhaps you should try creating a new user manually through the console using `Spina::User.create name: "blabla", email: "bla@bla.com", password: "blabla", admin: true`

**Comment by katielentes** [comment]
Thanks, that worked for me!

**Comment by katielentes** [comment]
Can I create a theme in a similar way? Right now `current_theme` is nil

**Comment by Bramjetten** [comment]
Yes, you can create a `Spina::Account` if you don’t have ona already and set it’s theme to `default` for example.
