### ISSUE TITLE
500 Error when uploading Image

### ISSUE THREAD

**Issue by codyrickman** [SpinaCMS/Spina#527]
`Started POST "/rails/active_storage/direct_uploads" for ::1 at 2020-02-21 21:53:11 -0500
Processing by ActiveStorage::DirectUploadsController#create as JSON
  Parameters: {"blob"=>{"filename"=>"DSC09131.jpg", "content_type"=>"image/jpeg", "byte_size"=>108844, "checksum"=>"2bbDxJTRUFJjfRUdJDFw5g=="}, "direct_upload"=>{"blob"=>{"filename"=>"DSC09131.jpg", "content_type"=>"image/jpeg", "byte_size"=>108844, "checksum"=>"2bbDxJTRUFJjfRUdJDFw5g=="}}}
Completed 500 Internal Server Error in 68ms (ActiveRecord: 41.2ms)

ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "active_storage_blobs" does not exist
LINE 8:                WHERE a.attrelid = '"active_storage_blobs"'::...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
                     c.collname, col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a
                LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                LEFT JOIN pg_type t ON a.atttypid = t.oid
                LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
               WHERE a.attrelid = '"active_storage_blobs"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
):`

**Comment by Bramjetten** [comment]
You have to install ActiveStorage first!

**Comment by codyrickman** [comment]
Git it thanks! However, not I am having an issue retrieving the image url from the part. 

<%= image_tag @page.content(:header_image).try(:file_url) %> returns nil so it cannot build a uri.

**Comment by Bramjetten** [comment]
Try `image_tag @page.content(:header_image).variant(resize: "500x500")`
