### ISSUE TITLE
Unable to generate/bootstrap custom pages

### ISSUE THREAD

**Issue by mhoelter** [SpinaCMS/Spina#534]
I've added a new custom page config in `config/initializes/themes/default.rb`, along with the accompanying view file (`views/default/pages/contact.html.erb`). However, I'm unable to get Spina to create the new page in the Admin dashboard. 

[In the docs](https://www.spinacms.com/guide/themes/custom-pages), it says Spina will create the page when bootstrapping the website, but I'm unable to figure out how to do this and make it work.

I've tried:

1. Restarting the server.
2. Running `rails spina:bootstrap`/`rake spina:bootstrap`
3. Running `rails g spina:install`

Any help would be very much appreciated! For further context, I'm trying to add this page to an already existing Spina site, which may make a difference.

My new custom page config:

```
theme.custom_pages = [{
    name:           'homepage',
    title:          'Homepage',
    deletable:      false,
    view_template:  'homepage'
  }, {
    name:           'contact',
    title:          'Contact',
    deletable:      false,
    view_template:  'contact'
  }]

**Comment by Bramjetten** [comment]
Try this: go to the admin panel to preferences > styling and click "Save styling".

**Comment by mhoelter** [comment]
@Bramjetten Thanks for your reply. I tried saving the styling but it did not work. I tried a few combinations of saving and restarting the server as well, but to no avail.

**Comment by Bramjetten** [comment]
Did you also add a view_template `contact` to `theme.view_templates`?

**Comment by mhoelter** [comment]
@benlovell I did not! But after adding that part and saving the styling as you said, it solved the issue! Thank you very much.

**Comment by Bramjetten** [comment]
Thanks for your quick response and feedback. I'll make it more clear in our documentation. 

Also, we have a nice Slack community which you can join: https://slack-spinacms.herokuapp.com lots of helpful people around!

**Comment by benlovell** [comment]
> @benlovell I did not! But after adding that part and saving the styling as you said, it solved the issue! Thank you very much.

I don't think you meant to @ me.
