### ISSUE TITLE
Getting Warning - Does Spina run with Rails 6.0.2.2? 

### ISSUE THREAD

**Issue by shukhrat2001** [SpinaCMS/Spina#537]
I am running Ruby 2.6.6 and Rails 6.0.2.2 and have added the gem 'spina' into my Gemfile. 
This project is connected to postgresql so everything was smooth until I run 'Rails s' command at the end localhost gets stuck and I can't close the command prompt by pressing Ctrl C. 

Does spina run with Rails 6.0.2.2?

Can you point me to the right direction? What am I doing wrong?

Thanks in advance!

-----------

Booting Puma
=> Rails 6.0.2.2 application starting in development
=> Run `rails server --help` for more startup options
*** SIGUSR2 not implemented, signal based restart unavailable!
*** SIGUSR1 not implemented, signal based restart unavailable!
*** SIGHUP not implemented, signal based logs reopening unavailable!
Puma starting in single mode...
* Version 4.3.3 (ruby 2.6.6-p146), codename: Mysterious Traveller
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://[::1]:3000
* Listening on tcp://127.0.0.1:3000
Use Ctrl-C to stop
Started GET "/demo/admin" for 127.0.0.1 at 2020-04-17 16:37:39 -0400
   (2.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by Spina::PagesController#show as HTML
  Parameters: {"id"=>"demo/admin"}
  Spina::Page Load (4.2ms)  SELECT "spina_pages".* FROM "spina_pages" INNER JOIN "spina_page_translations" "spina_page_translations_en" ON "spina_page_translations_en"."spina_page_id" = "spina_pages"."id" AND "spina_page_translations_en"."locale" = 'en' WHERE "spina_page_translations_en"."materialized_path" = '/demo/admin' LIMIT $1  [["LIMIT", 1]]
  Spina::RewriteRule Load (2.6ms)  SELECT "spina_rewrite_rules".* FROM "spina_rewrite_rules" WHERE "spina_rewrite_rules"."old_path" = $1 LIMIT $2  [["old_path", "/demo/admin"], ["LIMIT", 1]]
  Rendering public/404.html
  Rendered public/404.html (Duration: 7.0ms | Allocations: 5)
Completed 404 Not Found in 704ms (Views: 51.5ms | ActiveRecord: 17.0ms | Allocations: 78698)

Started GET "/" for 127.0.0.1 at 2020-04-17 16:37:48 -0400
Processing by Spina::PagesController#homepage as HTML
  Spina::Page Load (0.4ms)  SELECT "spina_pages".* FROM "spina_pages" WHERE "spina_pages"."name" = $1 LIMIT $2  [["name", "homepage"], ["LIMIT", 1]]
  CACHE Spina::Page Load (0.0ms)  SELECT "spina_pages".* FROM "spina_pages" WHERE "spina_pages"."name" = $1 LIMIT $2  [["name", "homepage"], ["LIMIT", 1]]
  CACHE Spina::Page Load (0.0ms)  SELECT "spina_pages".* FROM "spina_pages" WHERE "spina_pages"."name" = $1 LIMIT $2  [["name", "homepage"], ["LIMIT", 1]]
  Spina::Account Load (1.7ms)  SELECT "spina_accounts".* FROM "spina_accounts" ORDER BY "spina_accounts"."id" ASC LIMIT $1  [["LIMIT", 1]]
  Rendering demo/pages/homepage.html.haml within layouts/demo/application
  Spina::Page::Translation Load (0.3ms)  SELECT "spina_page_translations".* FROM "spina_page_translations" WHERE "spina_page_translations"."spina_page_id" = $1  [["spina_page_id", 1]]
  ↳ app/views/demo/pages/homepage.html.haml:1
  Spina::PagePart Load (1.7ms)  SELECT "spina_page_parts".* FROM "spina_page_parts" WHERE "spina_page_parts"."page_id" = $1 AND "spina_page_parts"."name" = $2 LIMIT $3  [["page_id", 1], ["name", "text"], ["LIMIT", 1]]
  ↳ app/views/demo/pages/homepage.html.haml:2
  Rendered demo/pages/homepage.html.haml within layouts/demo/application (Duration: 164.5ms | Allocations: 21797)
WARNING on line 335, column 20 of C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/spina-1.1.3/app/assets/stylesheets/spina/_forms.sass:
Compound selectors may no longer be extended.
Consider `@extend .icon-large-check, :before` instead.
See http://bit.ly/ExtendCompound for details.

WARNING on line 764, column 22 of C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/spina-1.1.3/app/assets/stylesheets/spina/_forms.sass:
Compound selectors may no longer be extended.
Consider `@extend .icon-upload-outline, :before` instead.
See http://bit.ly/ExtendCompound for details.

WARNING on line 772, column 22 of C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/spina-1.1.3/app/assets/stylesheets/spina/_forms.sass:
Compound selectors may no longer be extended.
Consider `@extend .icon-refresh, :before` instead.
See http://bit.ly/ExtendCompound for details.

WARNING on line 101, column 22 of C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/spina-1.1.3/app/assets/stylesheets/spina/_tables.sass:
Compound selectors may no longer be extended.
Consider `@extend .icon-caret-up, :before` instead.
See http://bit.ly/ExtendCompound for details.

WARNING on line 104, column 15 of C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/spina-1.1.3/app/assets/stylesheets/spina/_tables.sass:
Compound selectors may no longer be extended.
Consider `@extend .icon-caret-down, :before` instead.
See http://bit.ly/ExtendCompound for details.

WARNING on line 264, column 22 of C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/spina-1.1.3/app/assets/stylesheets/spina/_tables.sass:
Compound selectors may no longer be extended.
Consider `@extend .icon-caret-down, :before` instead.
See http://bit.ly/ExtendCompound for details.

WARNING on line 269, column 22 of C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/spina-1.1.3/app/assets/stylesheets/spina/_tables.sass:
Compound selectors may no longer be extended.
Consider `@extend .icon-caret-up, :before` instead.
See http://bit.ly/ExtendCompound for details.

WARNING on line 200, column 20 of C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/spina-1.1.3/app/assets/stylesheets/spina/_gallery.sass:
Compound selectors may no longer be extended.
Consider `@extend .icon-large-check, :before` instead.
See http://bit.ly/ExtendCompound for details.

WARNING on line 263, column 22 of C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/spina-1.1.3/app/assets/stylesheets/spina/_gallery.sass:
Compound selectors may no longer be extended.
Consider `@extend .icon-refresh, :before` instead.
See http://bit.ly/ExtendCompound for details.

WARNING on line 50, column 17 of C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/spina-1.1.3/app/assets/stylesheets/spina/_trix_custom.sass:
Compound selectors may no longer be extended.
Consider `@extend .icon-bold, :before` instead.
See http://bit.ly/ExtendCompound for details.

WARNING on line 54, column 17 of C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/spina-1.1.3/app/assets/stylesheets/spina/_trix_custom.sass:
Compound selectors may no longer be extended.
Consider `@extend .icon-italic, :before` instead.
See http://bit.ly/ExtendCompound for details.

WARNING on line 58, column 17 of C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/spina-1.1.3/app/assets/stylesheets/spina/_trix_custom.sass:
Compound selectors may no longer be extended.
Consider `@extend .icon-strikethrough, :before` instead.
See http://bit.ly/ExtendCompound for details.

WARNING on line 62, column 17 of C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/spina-1.1.3/app/assets/stylesheets/spina/_trix_custom.sass:
Compound selectors may no longer be extended.
Consider `@extend .icon-link, :before` instead.
See http://bit.ly/ExtendCompound for details.

**Comment by kofekid** [comment]
Same here. The workaround is to specify in Gemfile. While the fix is being delivered
`gem 'spina', '= 1.1.2`
