### ISSUE TITLE
Can't resolve image into URL: undefined method `to_model'

### ISSUE THREAD

**Issue by osborng** [SpinaCMS/Spina#539]
the "image_tag content(:image).variant(resize: "200x100")" code in the demo page view throws the following error when browsing to the page after selecting an image in the admin area.
Can't resolve image into URL: undefined method `to_model' for #<ActiveStorage::Variant:0x00007fb83c775848>

Ruby version: 2.7.1
Rails version: 6.0.2.2
Spina version: latest master commit 

Image display works properly when adding an image in the text section of the demo page.

**Comment by Bramjetten** [comment]
Try:
`image_tag main_app.url_for(content(:image).variant(resize: "200x100"))`

**Comment by osborng** [comment]
That resolved the issue. Thank you.
