### ISSUE TITLE
Response as JSON

### ISSUE THREAD

**Issue by ezitisitis** [SpinaCMS/Spina#549]
New to Rails, new to Spina.

**NB! This is not an issue, but question**

Is there an option to get page content as JSON, I want to make an back-end and front-end separated. So I currently create an routes like "/api/v1/home" pointing to "api#home", but stuck in moment how to get Homepage Page data from Spina to create an JSON response.

Will be glad for help.

**Comment by Bramjetten** [comment]
You’re in luck! We’re currently finishing #543 which is all about JSON. Feel free to try it out.

**Comment by ezitisitis** [comment]
Oh! Nice, will check!

Should I close the issue, or it can stay while #543 is not merged, just in case if any one else with similar question will appear?
