### ISSUE TITLE
Spina routes conflicts with my app routes

### ISSUE THREAD

**Issue by WhipFalcon** [SpinaCMS/Spina#572]
In my application works only Spina routes. I have PageController and when i try to open page configured with my PageController, i catch the 404 error. I figured out that app refers to Spina::PagesController, not to mine. How can i fix it?

**Comment by Bramjetten** [comment]
You can set `config.disable_frontend_routes = true` in `spina.rb`. Then you can add your own routes to your own PagesController in your `routes.rb` file. Here's the current frontend routes Spina uses:

```ruby
# Frontend
root to: "pages#homepage"

# Pages
get '/:locale/*id' => 'pages#show', constraints: {locale: /#{Spina.config.locales.join('|')}/ }
get '/:locale/' => 'pages#homepage', constraints: {locale: /#{Spina.config.locales.join('|')}/ }
get '/*id' => 'pages#show', as: "page", controller: 'pages', constraints: lambda { |request|
  (!(Rails.env.development? && request.env['PATH_INFO'].starts_with?('/rails/') || request.env['PATH_INFO'].starts_with?("/#{Spina.config.backend_path}") || request.env['PATH_INFO'].starts_with?('/attachments/'))) && request.path.exclude?("rails/active_storage")
}
```

**Comment by WhipFalcon** [comment]
This works for me! Thanks a lot!
