### ISSUE TITLE
Trix editor blocks should keep the toolbar visible at all times

### ISSUE THREAD

**Issue by simmerz** [SpinaCMS/Spina#579]
When writing long-form text content (such as blogs), the toolbar goes out of sight and so there's a lot of scrolling up and down to add links, images etc.

A quick and dirty (read hacky) solution seems to be `position: sticky; top: 117px;` but that assumes the header bar is always the same size across plugins and pages, which we shouldn't necessarily assume.

**Comment by Bramjetten** [comment]
Instead of "at all times", I'd opt for on focus only.

**Comment by Bramjetten** [comment]
Created a PR that fixes this (#584)
