### ISSUE TITLE
Edit page broken on 2.0.0.alpha

### ISSUE THREAD

**Issue by simmerz** [SpinaCMS/Spina#609]
https://github.com/SpinaCMS/Spina/blob/8b7d163c3d617f6e5604244dcf32aadc58bfe510/app/views/spina/admin/pages/_form_page_seo.html.haml#L24

Is preventing the edit form from loading. Looks like the `url_title` method.

<img width="1090" alt="screenshot_2020-08-14_at_21 39 20" src="https://user-images.githubusercontent.com/24327/90292456-cf62f700-de79-11ea-9f04-335c68ad0abe.png">

**Comment by Bramjetten** [comment]
Closing this since the method was overwritten locally

**Comment by abunsen** [comment]
@Bramjetten What do you mean by this? I'm using Spina 1.2.0 and encountered this.

**Comment by abunsen** [comment]
Had to run: `rails spina:install:migrations`
