### ISSUE TITLE
html5shiv invalid CDN resource

### ISSUE THREAD

**Issue by kahrpatrick** [SpinaCMS/Spina#645]
The external resource `https://html5shiv.googlecode.com/svn/trunk/html5.js` is loaded in a few places in Spina. The googlecode CDN however doesn't exist any more.

Either remove entirely, or replace by one of the CDNs listed here: https://cdnjs.com/libraries/html5shiv

**Comment by Bramjetten** [comment]
Thanks for the find! Will be removed entirely.

**Comment by Bramjetten** [comment]
Fixed in #664
