### ISSUE TITLE
Wrong materialized path on (resource) pages with same title

### ISSUE THREAD

**Issue by kahrpatrick** [SpinaCMS/Spina#655]
I discovered that Spina generates the same materialized path for resource pages with the same title if more than 2 pages share the same title.

Example:

Page 1: 
**title**: Example
**materialized path**: `/slug/example`

Page 2:
**title**: Example
**materialized path**: `/slug/example-1`

Page 3:
**title**: Example
**materialized path**: `/slug/example-1`

In fact, the counter is never incremented.

**Comment by Bramjetten** [comment]
I had a look at it and I think it's fixed in #656.
