### ISSUE TITLE
//html5shiv.googlecode.com/svn/trunk/html5.js returns 404s

### ISSUE THREAD

**Issue by corporealfunk** [SpinaCMS/Spina#663]
Looks like googlecode no longer hosts the html5shiv code. Other CDNs still carry it, though.

This is referenced in:

app/views/layouts/spina/admin/admin.html.haml
app/views/layouts/spina/login.html.haml
app/assets/icons/spina/preview/ics_spina-preview.html
app/assets/icons/spina/preview/icons_spina-preview.html

**Comment by Bramjetten** [comment]
Fixed in #664
