### ISSUE TITLE
Headless CMS Abilities?

### ISSUE THREAD

**Issue by robskrob** [SpinaCMS/Spina#672]
Hello, I hope this is the appropriate place for a general question. If it is not please let me know.

Can SpinaCMS work as a headless CMS? I'd like to have Spina provide a JSON API for a staticly served [Nuxt site](https://nuxtjs.org/), and I was wondering if folks here have accomplished this. If so, is there any documentation / blog posts / content online that shows how to set up Spina as a headless CMS?

**Comment by Bramjetten** [comment]
I haven’t done this in production, but it shouldn’t be too hard. Because pages are already stored as JSON, building an API should be trivial. One challenge could be the way you handle images though.

**Comment by robskrob** [comment]
thank you @Bramjetten ! Hopefully I can schedule some time in soon to take care of this. Maybe I can report back with reproducible steps here, or perhaps I can make a PR to add documentation / guides for setting up a headless Spina CMS.

I'll close out the issue.
