### ISSUE TITLE
`table_structure': Could not find table 'spina_accounts' (ActiveRecord::StatementInvalid)

### ISSUE THREAD

**Issue by mimikq** [SpinaCMS/Spina#674]
hi all 

me new in gem rails and ruby and i'm trying to get spinaCMS works but everytime i tried to install it i got this error thanks in advance.

`table_structure': Could not find table 'spina_accounts' (ActiveRecord::StatementInvalid)

**Comment by Bramjetten** [comment]
Did you follow the getting started guide and run the installer? It should copy and run Spina’s migrations.

**Comment by mimikq** [comment]
Hi @Bramjetten 

sry me totally new to rails , gem , ruby. so the how to install on official page and github was not clear beacuse me new to this, so i google page example : https://websiteforstudents.com/install-spinacms-ruby-on-rails-on-ubuntu-16-04-18-04-18-10/

before i had issue with racc during instalation and i find out that i needed ruby-dev, 

and if there is needed some DB migration i need to check it again, and i was thinking that no DB migration need and will create DB with installation. 

mean time i check and it looks like you mean this part, 



sry if this question is so .... 


mean time during writing this i find this step on official page, 

```Install Spina CMS
Start by creating a new Rails app using a PostgreSQL database.

rails new yourwebsite --database=postgresql``` 

so maybe this part is missing my bad . 

BR
mimik

**Comment by Bramjetten** [comment]
Alright! Here you can get the getting started guide:
https://www.spinacms.com/guide/getting-started/installing-spina#main
