### ISSUE TITLE
Move precompiled Spina assets to vendor/assets

### ISSUE THREAD

**Issue by Bramjetten** [SpinaCMS/Spina#712]
In production Spina adds stylesheets to `app/assets` after precompiling. This can cause issues with existing stylesheets using `require_tree .`. 

Instead, Spina should add stylesheets to `vendor/assets`.

**Comment by kbuckler** [comment]
+1 on moving to vendor/assets! Is there a reason to not have a full dependency on https://github.com/rails/tailwindcss-rails and have webpacker/asset pipeline handle the purging step? I suppose that it would complicate installation a little.

**Comment by Bramjetten** [comment]
We’re using a custom build of Tailwind right now, which tailwindcss-rails does not support. Also: that gem requires you to set a CSS compressor for the main app doing the purging. I much prefer to let Spina do the purging on just the Spina stylesheet so it doesn’t interfere with the main app.
