### ISSUE TITLE
Media Picker modal doesn't reopen if closed without choosing an image

### ISSUE THREAD

**Issue by corporealfunk** [SpinaCMS/Spina#726]
When I click "Choose Image" from the Spina::Image part UI from a page, the media picker modal opens. If I do not choose any images, and instead press "ESC" or click outside of the modal area, the modal closes.

However, if click again on "Choose Image", the modal does not open again.

(If I click on "Choose Image" on a different Spina::Image the modal will open for that target. And then the first target is valid again.)

![media_picker_bug](https://user-images.githubusercontent.com/451907/123330093-9371d700-d50b-11eb-8f8d-66560bb5c323.gif)

**Comment by silva96** [comment]
@Bramjetten just to be clear, this "[fix](https://github.com/SpinaCMS/Spina/issues/723)" actually didn't fix the problem of visiting same url within the same turbo frame?

**Comment by Bramjetten** [comment]
@silva96 Correct. You can never visit the same GET url twice on a turbo frame as of right now.

**Comment by silva96** [comment]
It's crazy how many hours I thought I was doing something wrong, but actually the bug wasn't fixed at all in beta-7, everyone who reads that issue would thing it's solved and they have the problem for other reason

**Comment by Bramjetten** [comment]
Same here. It’s not a bug though, apparently this is how it’s designed.
