### ISSUE TITLE
How to use existing users

### ISSUE THREAD

**Issue by Mbuckley0** [SpinaCMS/Spina#736]
I want to integrate Spina into an existing rails app I have and have the existing admin users have access to the admin area of spina and have certain restrictions around who can view the frontend pages. Is this possible?

**Comment by Bramjetten** [comment]
Currently, you'd have to override the `current_spina_user` method. We're working on a new authentication system where you can easily swap it out though.

**Comment by Mbuckley0** [comment]
Thanks that works. Is that documented anywhere?
