### ISSUE TITLE
When a site has many image folders, the media picker doesn't have a scrollbar

### ISSUE THREAD

**Issue by corporealfunk** [SpinaCMS/Spina#761]
When a site has many media folders, when the media picker pops open, the images div has a scrollbar, but not the folders list, so the folders later down are inaccessible.

![Screen Shot 2021-08-02 at 10 49 11 AM](https://user-images.githubusercontent.com/451907/127880819-f2b63ef3-88cc-4ebd-9219-97d126bdc08e.png)

**Comment by Bramjetten** [comment]
That’s a lot of folders, nice! We’ll fix this 👍
