### ISSUE TITLE
Admin dashboard broken in Firefox

### ISSUE THREAD

**Issue by kahrpatrick** [SpinaCMS/Spina#792]
There seems to be an issue with `es-module-shims` in Firefox that breaks all JS interaction.

![Screenshot_20210821_112602](https://user-images.githubusercontent.com/18963412/130320311-b27cc7fd-a51d-4f3e-a0ba-defa5aba5d7e.png)
![Screenshot_20210821_132059](https://user-images.githubusercontent.com/18963412/130320316-0652c00b-9d70-434b-911b-68493c2c51fc.png)

Browser: Firefox 91.0.1 (on Ubuntu 20.04.3 LTS )
Spina: 2.3.4

**Comment by Bramjetten** [comment]
Error seemed to be related to Trix. Switching to an ESM-compatible build (same as Rails 7 is currently using) of Trix looks to solve the issue: #793
