### ISSUE TITLE
Add a silent option to the installer ?

### ISSUE THREAD

**Issue by bdavidxyz** [SpinaCMS/Spina#880]
It is a feature request. It would be lovely to give the possibility to install Spina without asking any question to the user.

So when doing
```
rails g spina:install
```

It would be nice that there is an option --silent so that Spina could be used inside a rails generator without interrupting the process. In this case, default options would apply.

```
rails g spina:install --silent
```

Would install Spina with default values.

**Comment by Bramjetten** [comment]
I really like this suggestion. Feel free to open a PR 👍

**Comment by bdavidxyz** [comment]
Thanks, just opened a PR about it : https://github.com/SpinaCMS/Spina/pull/881
I can't assign a reviewer, but I think the PR is done and need a review. Best regards.

**Comment by Bramjetten** [comment]
Thanks a lot! Merged 👍
