### ISSUE TITLE
Navigations that get added are not showing up in the admin UI

### ISSUE THREAD

**Issue by leemcalilly** [SpinaCMS/Spina#883]
I'm setting up my first Spina project and when I try to add the example custom navigation in the docs, it doesn't appear in the admin UI.

```
theme.navigations = [{
    name: 'main',
    label: 'Main navigation',
    auto_add_pages: true
  }, {
    name: 'mobile',
    label: 'Mobile'
  }]
```

I did not have this problem with theme.parts or theme.layout_parts. Obviously tried restarting the server and had this same issue in Safari and Chrome. (See attached screenshot).

<img width="1394" alt="Screen Shot 2021-11-08 at 5 36 07 PM" src="https://user-images.githubusercontent.com/280966/140835163-fb834915-dc2f-4b32-acd1-09425481f416.png">

<img width="945" alt="Screen Shot 2021-11-08 at 5 35 41 PM" src="https://user-images.githubusercontent.com/280966/140835172-5fdb4c64-be84-4adf-b203-e9a2d8a9b96c.png">

**Comment by Bramjetten** [comment]
The navigations are created as records in the database, you can run `rails spina:bootstrap` to run the callbacks that create them. Sorry, I should clarify this in the documentation!

**Comment by leemcalilly** [comment]
Ok. Got it. Thanks!
