### ISSUE TITLE
Remove Sprocket dependency

### ISSUE THREAD

**Issue by damienlethiec** [SpinaCMS/Spina#928]
Hi there :)

Do you plan to remove the Sprocket dependency of the gem in the future? I usually don't include it in my apps anymore and it is a bit sad to put it back for Spina ;)

Thanks a ton,
Damien

**Comment by damienlethiec** [comment]
Thanks for the answer

**Comment by damienlethiec** [comment]
I am trying to use the rich text field but it does not seems to work properly. I cannot click on bold and italic and the icon for attachment is not present. The others seem to work fine. Could it be related to this? I installed sprocket to be able to use Spina but only the bare minimum.

Thanks so much for this !

![image](https://user-images.githubusercontent.com/8105430/148609388-66ba2663-6aa3-4ce3-aa1f-65f9effb2222.png)

**Comment by damienlethiec** [comment]
I could take a video if you want. It would probably be clearer

**Comment by Bramjetten** [comment]
Are you getting any errors in your console?

**Comment by damienlethiec** [comment]
No related errors (only the warnings triggered by rails 7)

**Comment by Bramjetten** [comment]
Perhaps you can try adding the sprockets-rails gem instead.

**Comment by damienlethiec** [comment]
I already installed it to be able to use Spina :)
