### ISSUE TITLE
How to run request specs on Spina pages

### ISSUE THREAD

**Issue by damienlethiec** [SpinaCMS/Spina#929]
Hello there,

I am trying to run request specs on my Spina custom pages (I manage the routes myself). Unfortunately, when I do my get to the path, I receive the following error.

```
NoMethodError:
        undefined method `theme' for nil:NilClass

                Spina::Current.theme ||= ::Spina::Theme.find_by_name(current_account.theme)
```

Do you have good practices on how to test pages where Spina is used as the CMS?

Thanks a ton !

**Comment by Bramjetten** [comment]
You need to have a Spina::Account record with a theme in order to use Spina. You can add that to your test setup.

**Comment by damienlethiec** [comment]
Thanks ! I will try at the beginning of next week. Would you have an example by any chance?

**Comment by damienlethiec** [comment]
It works !! Sorry for the stupid question :)
