### ISSUE TITLE
TRIX with positionable images

### ISSUE THREAD

**Issue by pgruener** [SpinaCMS/Spina#931]
With the original trix editor (https://trix-editor.org/) it's possible to align images next to each other.

![image](https://user-images.githubusercontent.com/110686/148678387-fd51ca55-9f33-4ca5-aaa8-2a3ea842d10c.png)

Those a functionality would also be really helpful in the CMS.

Also if there would be an option to put the image next to a text.

**Comment by Bramjetten** [comment]
You can put multiple images next to each other, they're `inline-block`. It's up to you how to style them in your frontend though.

<img width="621" alt="CleanShot 2022-01-14 at 13 56 50@2x" src="https://user-images.githubusercontent.com/423116/149518861-070d0056-7dd2-4230-84ff-3aa41d4da9cd.png">

**Comment by pgruener** [comment]
Ok, that is what I am looking for, but it is not possible in my setup. Perhaps it is because of #930 ?

**Comment by Bramjetten** [comment]
Correct, will be fixed shortly!

**Comment by pgruener** [comment]
Great job Bram!

**Comment by Bramjetten** [comment]
Merged!
