### ISSUE TITLE
Feature Request : Use part description as field hint

### ISSUE THREAD

**Issue by vpiau** [SpinaCMS/Spina#945]
Hi,

First, thank you so much for this amazing work 🙏

As  parts `title` property is used as field label in admin side, it would be great if we could use `description` as hint for corresponding field in admin form.

```ruby
theme.parts = [{
    name:         'content',
    title:        'Content',
    description:  'Hint text to be displayed under admin field',
    part_type:    'Spina::Parts::Text'
}]
```

**Comment by Bramjetten** [comment]
I agree! That would be cool. How about actually calling it “hint” instead of description?

**Comment by dokeop** [comment]
This was also my final thought, ideally with could use a `hint` property to achieve this.

**Comment by Bramjetten** [comment]
Something like this?
<img width="918" alt="CleanShot 2022-01-17 at 21 00 44@2x" src="https://user-images.githubusercontent.com/423116/149830776-32961d85-8ceb-4938-bf64-614e86a72f38.png">

**Comment by Bramjetten** [comment]
Created a PR #946

**Comment by vpiau** [comment]
Yes exactly ! Or maybe with hint under field 👍 

<img width="983" alt="image" src="https://user-images.githubusercontent.com/59887190/149831261-5a1877e9-0b95-4c2b-9ee8-1a43c9c7e57e.png">

With the corresponding example from Tailwind UI :

```html
<div class="max-w-5xl">
  <label class="font-medium text-gray-700">Title</label>
  <input placeholder="Title" class="mt-1 form-input font-medium block w-full max-w-5xl  px-4 py-3" data-controller="" type="text" value="Homepage" name="page[title]">
  <p class="mt-2 text-sm text-gray-500">The main page title</p>
</div>  
```

**Comment by vpiau** [comment]
well done !
