### ISSUE TITLE
How to best set up development environment for contributing to Spina?

### ISSUE THREAD

**Issue by moxvallix** [SpinaCMS/Spina#994]
I am currently having a go at making Spina's UI more responsive, and I have directly cloned the project, and am running it as a Rails app.

However, it seems that Spina is using a pre-compiled version of Tailwind, and I am limited in what classes I can use.

Any tips / pointers on how to set up for contributing, like how to generate that Tailwind file to use the classes I need, and what best practices are for development in this app?

**Comment by Bramjetten** [comment]
In production when your assets are precompiled, Spina will generate a new build for you on the fly. 

In development you can run `rails spina:tailwind:watch` to watch for changes and create a new build. You can use the `Spina.config.tailwind_content` option to add paths to the array for Tailwind.

https://spinacms.com/docs/advanced/tailwind
